export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const FETCH_EMPLOYEES_PENDING = 'FETCH_EMPLOYEES_PENDING';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';
export const CHANGE_EMPLOYEES_ISARCHIVE = 'CHANGE_EMPLOYEES_ISARCHIVE';
export const CHANGE_PERSON_ISARCHIVE = 'CHANGE_PERSON_ISARCHIVE';
export const CHANGE_PERSON_ROLE = 'CHANGE_PERSON_ROLE';
export const CHANGE_PERSON_TEXT_INPUT = 'CHANGE_PERSON_TEXT_INPUT';
export const SAVE_PERSON = 'SAVE_PERSON';
export const SAVE_NEW_PERSON = 'SAVE_NEW_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';


