export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const FETCH_EMPLOYEES_PENDING = 'FETCH_EMPLOYEES_PENDING';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';
export const CHANGE_EMPLOYEES_ISARCHIVE = 'CHANGE_EMPLOYEES_ISARCHIVE';


